### ISSUE TITLE
Need help syncing to current directory

### ISSUE THREAD

**Issue by ninachristof** [eleanormally/cbug#11]
**Describe the bug**
Won't let me sync to working directory

**Screenshots**
<img width="1440" alt="Screen Shot 2023-02-08 at 11 52 57" src="https://user-images.githubusercontent.com/110969339/217598030-ad391ffc-978f-4026-bb06-983caa3a6f97.png">*
 - OS: [e.g. macOS Venture 13.1]
 - Version [e.g cbug v1.0.1]

**Additional context**

**Comment by eleanormally** [comment]
It seems you aren't calling it with the full path. On the line at the top, you type `~/Downloads/cbug/bin/cbug`, whereas below you just use `cbug`. to be able to call the tool with the just the `cbug` command, you must set up an alias as described in the [wiki](https://github.com/eleanormally/cbug/wiki), or invoke its full path ( `~/Downloads/cbug/bin/cbug`) every time
