### ISSUE TITLE
runtime error

### ISSUE THREAD

**Issue by michaelhelper** [eleanormally/cbug#7]
**Describe the bug**
the runtime exec fails every time I try to run cbug. 

**To Reproduce**
cbug ./fileName.out

**Expected behavior**
Should return memory report

**Screenshots**
![Image 2-1-23 at 5 15 PM](https://user-images.githubusercontent.com/100871194/216175951-475195a8-85a3-4648-8345-22d62cb09fa2.jpg)

**Additional context**
No TA was able to fix the problem

**Comment by eleanormally** [comment]
Was this compiled outside of cbug? Because it is being run in a virtual machine, you must use g++ from within cbug.
